config/routes.rb
Rails.application.routes.draw do

  resources :workouts
  root 'workouts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all.order("created_at DESC")
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end


  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: {class: "form-horizonal"}) do |f|
  = f.input :date, label: "Date", input_html: {class: "form-inline"}
  = f.input :workout, label: "What area did you workout?"
  = f.input :mood, label: "How were you feeling?"
  = f.input :length, label: "How long was the workout?"
  %br/
  = f.button :submit, {class: "btn btn-primary"}

app/views/workouts/edit.html.haml
%h1 Edit Workout

= render 'form'

%br/

= link_to 'Cancel', root_path, {class: "btn btn-primary"}

app/views/workouts/index.html.haml
- @workouts.each do |workout|
  %h2= link_to workout.date, workout
  %h3= workout.workout

app/views/workouts/new.html.haml
%h1 New Workout

= render 'form'

%br/

= link_to 'Cancel', root_path, {class: "btn btn-primary"}

app/views/workouts/show.html.haml
#workout
  %p= @workout.date
  %p= @workout.workout
  %p= @workout.mood
  %p= @workout.length

  = link_to "Back", root_path
  = link_to "Edit", edit_workout_path(@workout)
  = link_to "Delete", workout_path(@workout), method: :delete, data: {confirm: "Are you sure?"}